# .github/workflows/deploy.yml
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
    inputs:
      specific_file: {}
  push:
    branches:
      - web-staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'web-staging'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        run: npm install -g pnpm


      - name: Generate structure file
        working-directory: ./website
        run: pnpm run generate-structure

      - name: Install Dependencies and Build
        working-directory: ./website
        run: |
          pnpm install
          pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist