name: Merge LaTeX files

on:
  workflow_dispatch:
    inputs:
      specific_file: {}
  push:
    branches:
      - master
    paths:
      - '**.tex'
      - '**/images/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Cache TeX Live installation
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-texlive
          restore-keys: |
            ${{ runner.os }}-apt-texlive

      - name: Install minimal TeX Live packages with lualatex support
        run: |
          if [ ! -d "/var/cache/apt/archives" ]; then
            sudo apt-get clean
            sudo apt-get update
          fi
          sudo apt-get install -y --no-install-recommends \
            texlive-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-luatex

      - name: Fix permissions
        run: |
          sudo chown -R runner:docker /var/lib/apt/lists/
          sudo chown -R runner:docker /var/cache/apt/archives/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run merge script for each subject
        run: |
          for dir in L1/*/; do
            if [ -d "$dir" ]; then
              echo "Processing $dir"
              python utils/merge "$dir"
            fi
          done
      
      - name: Convert newly generated .tex files to PDF
        run: |
          for texfile in $(find L1 -maxdepth 2 -name '*.tex' -not -path '*/originals/*'); do
            dir=$(dirname "$texfile")
            filename=$(basename "$texfile")
            echo "Processing $texfile in directory $dir"
            cd "$dir"
            lualatex -interaction=nonstopmode -halt-on-error "$filename"
            cd -  # Retourne au répertoire précédent
          done
      
      - name: Upload PDF artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: '**/*.pdf'