name: Merge TeX files and Convert LaTeX to PDF and Push to Branch

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '**.tex'
      - '**/images/**'

jobs:
  merge-and-convert-tex-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cache TeX Live installation
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-texlive
          restore-keys: |
            ${{ runner.os }}-apt-texlive

      - name: Install packages
        run: |
          if [ ! -d "/var/cache/apt/archives" ]; then
            sudo apt-get clean
            sudo apt-get update
          fi
          sudo apt-get install -y --no-install-recommends pandoc
          sudo apt-get install -y --no-install-recommends \
            texlive-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-luatex

      - name: Fix permissions
        run: |
          sudo chown -R runner:docker /var/lib/apt/lists/
          sudo chown -R runner:docker /var/cache/apt/archives/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run merge script for each subject
        run: |
          for dir in cours/*/; do
            for subject in $dir/*/; do
              if [ -d "$subject" ]; then
                echo "Processing $subject"
                python utils/merge "$subject"
              fi
            done
          done
      
      - name: Convert .tex files to HTML while preserving structure
        run: |
          pwd
          tree
          mkdir -p output/cours
          for dir in cours/*/; do
            for subject in $dir/*/; do
              mkdir -p output/$subject
              texfile=$(find $subject -name "*.tex" -mindepth 1 -maxdepth 1 -type f)
              lualatex -interaction=nonstopmode -halt-on-error --output-directory output/$subject/ "$texfile"
            done
          done
      
      - name: Commit and push converted HTML files
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "actions@github.com"
          git checkout -B web-staging
          cp -r output/* website/.
          git add website
          git commit -m "Update HTML files from LaTeX sources"
          git push origin web-staging --force