name: Merge LaTeX, convert to PDF and push to orphan branch
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  merge-and-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-science \
            texlive-luatex

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run merge script
        run: |
          for dir in cours/*; do
            for subject in $dir/*; do
              if [ -d "$subject" ]; then
                echo "Processing $subject"
                python utils/merge "$subject"
              fi
            done
          done
      
<<<<<<< HEAD
      - name: Convert to PDF
=======
      - name: Convert .tex files to PDF while preserving structure
>>>>>>> master
        run: |
          mkdir -p output/cours
          export TEXINPUTS=/home/runner/work/etude/etude/utils/:$TEXINPUTS
          for dir in cours/*; do
            for subject in $dir/*; do
              export TEXINPUTS=$subject:$TEXINPUTS
              mkdir -p output/$subject
              texfile=$(find $subject -name "*.tex" -mindepth 1 -maxdepth 1 -type f)
              lualatex -interaction=nonstopmode -halt-on-error --output-directory output/$subject/ "$texfile"
<<<<<<< HEAD
              lualatex -interaction=nonstopmode -halt-on-error --output-directory output/$subject/ "$texfile"
            done
          done

      - name: Push PDF files to pdf-output branch
        run: |
          git fetch origin pdf-output || true

          git checkout pdf-output || git checkout --orphan pdf-output

          find . -type f -name "*.pdf" -exec rm -f {} +

          find ./output/cours/ -type f -name "*.pdf" -exec cp {} ./ \;

          git add *.pdf

          git config user.name "Github Actions"
          git config user.email "actions@github.com"

          git commit -m "Update PDF files" || echo "No changes to commit"

          git push origin pdf-output --force
=======
              lualatex -interaction=nonstopmode -halt-on-error --output-directory output/$subject/ "$texfile" # do it again for toc ¯\_(ツ)_/¯
            done
          done
      
      - name: Commit and push converted PDF files
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "actions@github.com"
          git checkout -B web-staging
          
          mkdir -p website/public/static
          cp -r output/* website/public/static

          git add website
          git commit -m "Update PDF files from LaTeX sources"
          git push origin web-staging --force
>>>>>>> master
